# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SecurityTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SecurityTestApp
  pod 'AFNetworking', '2.5.0'

end
